/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/cactus/cactus.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: 'RootNode (gltf orientation matrix)' }}>
        <group userData={{ name: 'RootNode (model correction matrix)' }}>
          <group
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: 'Collada visual scene group' }}>
            <group userData={{ name: 'Sphere001' }}>
              <mesh
                material={materials['DefaultMaterial.002']}
                geometry={nodes.defaultMaterial.geometry}
                userData={{ name: 'defaultMaterial' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/cactus.glb');
